language: cpp
compiler:
  - clang
  - gcc

before_install:
  - wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
  - sudo apt-get install -qfy lttoolbox-dev libxml2-utils xsltproc libpcre3 zlib1g-dev apertium-dev autotools-dev libxml2-dev
script:
  - autoreconf -fvi
  - ./configure --with-yasmet
  - make -j4
  - make test
  - sudo make install
