#!/bin/bash

set -e -u -o pipefail

export VERBOSE=false
if [[ $# -ge 1 && $1 = -v ]]; then
    VERBOSE=true
fi

err () {
    if "$VERBOSE"; then
        sed "s/^/$1:	/"
    else
        cat >/dev/null
    fi
}

colournul () {
    local colour
    colour=$(printf '\033[0;36m') plain=$(printf '\033[0m')
    sed -e "s/\\x0/${colour}0&${plain}/g"
}


cd "$(dirname "$0")"
declare -i tests=0
declare -i failures=0
for xml in *.xml; do
    test=${xml%%.xml}
    rm -f "$test.{output,bin}"
    if ! (
			../src/apertium-validate-lrx "$test.xml" &&
				../src/lrx-comp "$test.xml" "$test.bin" &> >(err "$test") &&
                ../src/lrx-proc -m -z "$test.bin" < "$test.input" > "$test.output" 2> >(err "$test") &&
                diff -au "$test.expected" "$test.output" | colournul
        )
    then
        echo "$test: FAILED"
        (( failures++ )) || true
    fi
    (( tests++ )) || true
done
for bin in bincompat/*.bin; do
    test=$(basename "${bin%%.bin}")
    rm -f "$test.output"
    if ! (
            ../src/lrx-proc -m -z "${bin}" < "$test.input" > "$test.output" 2> >(err "$test") &&
                diff -au "$test.expected" "$test.output" | colournul
        )
    then
        echo "$test: FAILED"
        (( failures++ )) || true
    fi
    (( tests++ )) || true
done

$VERBOSE && printf "\nPASS: %s\nFAIL: %s\nTOTAL: %s\n" $(( tests - failures )) ${failures} ${tests}

if [[ $failures -gt 0 ]]; then
    exit 1
fi
