#!/usr/bin/python
# coding=utf-8
# -*- encoding: utf-8 -*-

import sys, codecs, copy, commands;

sys.stdin  = codecs.getreader('utf-8')(sys.stdin);
sys.stdout = codecs.getwriter('utf-8')(sys.stdout);
sys.stderr = codecs.getwriter('utf-8')(sys.stderr);

c = sys.stdin.read(1);

es_table = {

	'<adj><f><pl>' : '<adj>',
	'<adj><f><sg>' : '<adj>',
	'<adj><mf><pl>' : '<adj>',
	'<adj><mf><sg>' : '<adj>',
	'<adj><mf><sp>' : '<adj>',
	'<adj><m><pl>' : '<adj>',
	'<adj><m><sg>' : '<adj>',
	'<adj><pos><f><pl>' : '<adj><pos>',
	'<adj><pos><f><sg>' : '<adj><pos>',
	'<adj><pos><m><pl>' : '<adj><pos>',
	'<adj><pos><m><sg>' : '<adj><pos>',
	'<adj><sup><f><pl>' : '<adj>',
	'<adj><sup><f><sg>' : '<adj>',
	'<adj><sup><m><pl>' : '<adj>',
	'<adj><sup><m><sg>' : '<adj>',
	'<adv>' : '<adv>',
	'<adv><itg>' : '<adv><itg>',
	'<apos>' : '<apos>',
	'<cm>' : '<cm>',
	'<cnjadv>' : '<cnjadv>',
	'<cnjcoo>' : '<cnjcoo>',
	'<cnjsub>' : '<cnjsub>',
	'<det><def><f><pl>' : '<det><def>',
	'<det><def><f><sg>' : '<det><def>',
	'<det><def><m><pl>' : '<det><def>',
	'<det><def><m><sg>' : '<det><def>',
	'<det><def><nt><sg>' : '<det><def>',
	'<det><dem><f><pl>' : '<det><dem>',
	'<det><dem><f><sg>' : '<det><dem>',
	'<det><dem><m><pl>' : '<det><dem>',
	'<det><dem><m><sg>' : '<det><dem>',
	'<det><ind><f><pl>' : '<det><ind>',
	'<det><ind><f><sg>' : '<det><ind>',
	'<det><ind><mf><pl>' : '<det><ind>',
	'<det><ind><mf><sg>' : '<det><ind>',
	'<det><ind><mf><sp>' : '<det><ind>',
	'<det><ind><m><pl>' : '<det><ind>',
	'<det><ind><m><sg>' : '<det><ind>',
	'<det><itg><f><pl>' : '<det><itg>',
	'<det><itg><f><sg>' : '<det><itg>',
	'<det><itg><mf><sp>' : '<det><itg>',
	'<det><itg><m><pl>' : '<det><itg>',
	'<det><itg><m><sg>' : '<det><itg>',
	'<det><ord><f><pl>' : '<det><ord>',
	'<det><ord><f><sg>' : '<det><ord>',
	'<det><ord><m><pl>' : '<det><ord>',
	'<det><ord><m><sg>' : '<det><ord>',
	'<det><pos><f><pl>' : '<det><pos>',
	'<det><pos><f><sg>' : '<det><pos>',
	'<det><pos><mf><pl>' : '<det><pos>',
	'<det><pos><mf><sg>' : '<det><pos>',
	'<det><pos><m><pl>' : '<det><pos>',
	'<det><pos><m><sg>' : '<det><pos>',
	'<det><qnt><f><pl>' : '<det><qnt>',
	'<det><qnt><f><sg>' : '<det><qnt>',
	'<det><qnt><mf><pl>' : '<det><qnt>',
	'<det><qnt><mf><sg>' : '<det><qnt>',
	'<det><qnt><mf><sp>' : '<det><qnt>',
	'<det><qnt><m><pl>' : '<det><qnt>',
	'<det><qnt><m><sg>' : '<det><qnt>',
	'<guio>' : '<guio>',
	'<ij>' : '<ij>',
	'<lpar>' : '<lpar>',
	'<lquest>' : '<lquest>',
	'<mon>' : '<mon>',
	'<n><acr><f><pl>' : '<n>',
	'<n><acr><f><sg>' : '<n>',
	'<n><acr><m><sg>' : '<n>',
	'<n><f><pl>' : '<n>',
	'<n><f><sg>' : '<n>',
	'<n><f><sp>' : '<n>',
	'<n><mf><pl>' : '<n>',
	'<n><mf><sg>' : '<n>',
	'<n><mf><sp>' : '<n>',
	'<n><m><pl>' : '<n>',
	'<n><m><sg>' : '<n>',
	'<n><m><sp>' : '<n>',
	'<np><al><f><pl>' : '<np><al>',
	'<np><al><f><sg>' : '<np><al>',
	'<np><al><m><pl>' : '<np><al>',
	'<np><al><m><sg>' : '<np><al>',
	'<np><ant><f><sg>' : '<np><ant>',
	'<np><ant><m><sg>' : '<np><ant>',
	'<np><cog><mf><sg>' : '<np><cog>',
	'<np><loc><f><pl>' : '<np><loc>',
	'<np><loc><f><sg>' : '<np><loc>',
	'<np><loc><m><pl>' : '<np><loc>',
	'<np><loc><m><sg>' : '<np><loc>',
	'<num>' : '<num>',
	'<num><f><sp>' : '<num>',
	'<num><mf><pl>' : '<num>',
	'<num><mf><sg>' : '<num>',
	'<num><mf><sp>' : '<num>',
	'<num><mon>' : '<num><mon>',
	'<num><m><sp>' : '<num>',
	'<num><ord><f><sg>' : '<num><ord>',
	'<num><ord><m><sg>' : '<num><ord>',
	'<num><percent>' : '<num><percent>',
	'<num><time>' : '<num><time>',
	'<pr>' : '<pr>',
	'<preadv>' : '<preadv>',
	'<predet><f><pl>' : '<predet>',
	'<predet><f><sg>' : '<predet>',
	'<predet><m><pl>' : '<predet>',
	'<predet><m><sg>' : '<predet>',
	'<predet><nt><sp>' : '<predet>',
	'<prn><enc><p1><mf><pl>' : '<prn><enc>',
	'<prn><enc><p1><mf><sg>' : '<prn><enc>',
	'<prn><enc><p2><mf><pl>' : '<prn><enc>',
	'<prn><enc><p2><mf><sg>' : '<prn><enc>',
	'<prn><enc><p3><f><pl>' : '<prn><enc>',
	'<prn><enc><p3><f><sg>' : '<prn><enc>',
	'<prn><enc><p3><mf><pl>' : '<prn><enc>',
	'<prn><enc><p3><mf><sg>' : '<prn><enc>',
	'<prn><enc><p3><mf><sp>' : '<prn><enc>',
	'<prn><enc><p3><m><pl>' : '<prn><enc>',
	'<prn><enc><p3><nt>' : '<prn><enc>',
	'<prn><enc><ref><p3><mf><sp>' : '<prn><enc>',
	'<prn><itg><f><pl>' : '<prn><itg>',
	'<prn><itg><f><sg>' : '<prn><itg>',
	'<prn><itg><mf><pl>' : '<prn><itg>',
	'<prn><itg><mf><sg>' : '<prn><itg>',
	'<prn><itg><m><pl>' : '<prn><itg>',
	'<prn><itg><m><sg>' : '<prn><itg>',
	'<prn><pos><f><pl>' : '<prn><pos>',
	'<prn><pos><f><sg>' : '<prn><pos>',
	'<prn><pos><m><pl>' : '<prn><pos>',
	'<prn><pos><m><sg>' : '<prn><pos>',
	'<prn><pro><p1><mf><pl>' : '<prn><pro>',
	'<prn><pro><p1><mf><sg>' : '<prn><pro>',
	'<prn><pro><p2><mf><pl>' : '<prn><pro>',
	'<prn><pro><p2><mf><sg>' : '<prn><pro>',
	'<prn><pro><p3><f><pl>' : '<prn><pro>',
	'<prn><pro><p3><f><sg>' : '<prn><pro>',
	'<prn><pro><p3><mf><pl>' : '<prn><pro>',
	'<prn><pro><p3><mf><sg>' : '<prn><pro>',
	'<prn><pro><p3><mf><sp>' : '<prn><pro>',
	'<prn><pro><p3><m><pl>' : '<prn><pro>',
	'<prn><pro><p3><m><sg>' : '<prn><pro>',
	'<prn><pro><p3><nt>' : '<prn><pro>',
	'<prn><pro><ref><p3><mf><sp>' : '<prn><pro>',
	'<prn><tn><f><pl>' : '<prn><tn>',
	'<prn><tn><f><sg>' : '<prn><tn>',
	'<prn><tn><mf><pl>' : '<prn><tn>',
	'<prn><tn><mf><sg>' : '<prn><tn>',
	'<prn><tn><mf><sp>' : '<prn><tn>',
	'<prn><tn><m><pl>' : '<prn><tn>',
	'<prn><tn><m><sg>' : '<prn><tn>',
	'<prn><tn><m><sp>' : '<prn><tn>',
	'<prn><tn><nt>' : '<prn><tn>',
	'<prn><tn><p1><f><pl>' : '<prn><tn>',
	'<prn><tn><p1><mf><sg>' : '<prn><tn>',
	'<prn><tn><p1><m><pl>' : '<prn><tn>',
	'<prn><tn><p2><f><pl>' : '<prn><tn>',
	'<prn><tn><p2><mf><sg>' : '<prn><tn>',
	'<prn><tn><p2><m><pl>' : '<prn><tn>',
	'<prn><tn><p3><f><pl>' : '<prn><tn>',
	'<prn><tn><p3><f><sg>' : '<prn><tn>',
	'<prn><tn><p3><mf><pl>' : '<prn><tn>',
	'<prn><tn><p3><mf><sg>' : '<prn><tn>',
	'<prn><tn><p3><m><pl>' : '<prn><tn>',
	'<prn><tn><p3><m><sg>' : '<prn><tn>',
	'<prn><tn><ref><p3><mf><sp>' : '<prn><tn>',
	'<rel><aa><f><pl>' : '<rel><aa>',
	'<rel><aa><f><sg>' : '<rel><aa>',
	'<rel><aa><m><pl>' : '<rel><aa>',
	'<rel><aa><m><sg>' : '<rel><aa>',
	'<rel><adv>' : '<rel><adv>',
	'<rel><an><mf><sp>' : '<rel><an>',
	'<rel><an><nt>' : '<rel><an>',
	'<rel><nn><f><pl>' : '<rel><nn>',
	'<rel><nn><f><sg>' : '<rel><nn>',
	'<rel><nn><mf><pl>' : '<rel><nn>',
	'<rel><nn><mf><sg>' : '<rel><nn>',
	'<rel><nn><m><pl>' : '<rel><nn>',
	'<rel><nn><m><sg>' : '<rel><nn>',
	'<rel><nn><nt><sg>' : '<rel><nn>',
	'<rpar>' : '<rpar>',
	'<sent>' : '<sent>',
	'<vbhaver><cni><p1><pl>' : '<vbhaver>',
	'<vbhaver><cni><p3><pl>' : '<vbhaver>',
	'<vbhaver><cni><p3><sg>' : '<vbhaver>',
	'<vbhaver><fti><p1><pl>' : '<vbhaver>',
	'<vbhaver><fti><p1><sg>' : '<vbhaver>',
	'<vbhaver><fti><p2><pl>' : '<vbhaver>',
	'<vbhaver><fti><p3><pl>' : '<vbhaver>',
	'<vbhaver><fti><p3><sg>' : '<vbhaver>',
	'<vbhaver><fts><p3><pl>' : '<vbhaver>',
	'<vbhaver><fts><p3><sg>' : '<vbhaver>',
	'<vbhaver><ger>' : '<vbhaver><ger>',
	'<vbhaver><ifi><p3><pl>' : '<vbhaver>',
	'<vbhaver><ifi><p3><sg>' : '<vbhaver>',
	'<vbhaver><inf>' : '<vbhaver><inf>',
	'<vbhaver><pii><p1><pl>' : '<vbhaver>',
	'<vbhaver><pii><p2><sg>' : '<vbhaver>',
	'<vbhaver><pii><p3><pl>' : '<vbhaver>',
	'<vbhaver><pii><p3><sg>' : '<vbhaver>',
	'<vbhaver><pis><p1><pl>' : '<vbhaver>',
	'<vbhaver><pis><p3><pl>' : '<vbhaver>',
	'<vbhaver><pis><p3><sg>' : '<vbhaver>',
	'<vbhaver><pp><m><sg>' : '<vbhaver><pp>',
	'<vbhaver><pri><p1><pl>' : '<vbhaver>',
	'<vbhaver><pri><p1><sg>' : '<vbhaver>',
	'<vbhaver><pri><p2><pl>' : '<vbhaver>',
	'<vbhaver><pri><p2><sg>' : '<vbhaver>',
	'<vbhaver><pri><p3><pl>' : '<vbhaver>',
	'<vbhaver><pri><p3><sg>' : '<vbhaver>',
	'<vbhaver><prs><p1><pl>' : '<vbhaver>',
	'<vbhaver><prs><p2><sg>' : '<vbhaver>',
	'<vbhaver><prs><p3><pl>' : '<vbhaver>',
	'<vbhaver><prs><p3><sg>' : '<vbhaver>',
	'<vblex><cni><p1><pl>' : '<vblex>',
	'<vblex><cni><p2><sg>' : '<vblex>',
	'<vblex><cni><p3><pl>' : '<vblex>',
	'<vblex><cni><p3><sg>' : '<vblex>',
	'<vblex><fti><p1><pl>' : '<vblex>',
	'<vblex><fti><p1><sg>' : '<vblex>',
	'<vblex><fti><p2><pl>' : '<vblex>',
	'<vblex><fti><p2><sg>' : '<vblex>',
	'<vblex><fti><p3><pl>' : '<vblex>',
	'<vblex><fti><p3><sg>' : '<vblex>',
	'<vblex><fts><p1><pl>' : '<vblex>',
	'<vblex><fts><p2><sg>' : '<vblex>',
	'<vblex><fts><p3><pl>' : '<vblex>',
	'<vblex><fts><p3><sg>' : '<vblex>',
	'<vblex><ger>' : '<vblex><ger>',
	'<vblex><ifi><p1><pl>' : '<vblex>',
	'<vblex><ifi><p1><sg>' : '<vblex>',
	'<vblex><ifi><p2><pl>' : '<vblex>',
	'<vblex><ifi><p2><sg>' : '<vblex>',
	'<vblex><ifi><p3><pl>' : '<vblex>',
	'<vblex><ifi><p3><sg>' : '<vblex>',
	'<vblex><imp><p1><pl>' : '<vblex>',
	'<vblex><imp><p2><pl>' : '<vblex>',
	'<vblex><imp><p2><sg>' : '<vblex>',
	'<vblex><imp><p3><pl>' : '<vblex>',
	'<vblex><imp><p3><sg>' : '<vblex>',
	'<vblex><inf>' : '<vblex><inf>',
	'<vblex><pii><p1><pl>' : '<vblex>',
	'<vblex><pii><p2><pl>' : '<vblex>',
	'<vblex><pii><p2><sg>' : '<vblex>',
	'<vblex><pii><p3><pl>' : '<vblex>',
	'<vblex><pii><p3><sg>' : '<vblex>',
	'<vblex><pis><p1><pl>' : '<vblex>',
	'<vblex><pis><p2><pl>' : '<vblex>',
	'<vblex><pis><p2><sg>' : '<vblex>',
	'<vblex><pis><p3><pl>' : '<vblex>',
	'<vblex><pis><p3><sg>' : '<vblex>',
	'<vblex><pp><f><pl>' : '<vblex><pp>',
	'<vblex><pp><f><sg>' : '<vblex><pp>',
	'<vblex><pp><m><pl>' : '<vblex><pp>',
	'<vblex><pp><m><sg>' : '<vblex><pp>',
	'<vblex><pri><p1><pl>' : '<vblex>',
	'<vblex><pri><p1><sg>' : '<vblex>',
	'<vblex><pri><p2><pl>' : '<vblex>',
	'<vblex><pri><p2><sg>' : '<vblex>',
	'<vblex><pri><p3><pl>' : '<vblex>',
	'<vblex><pri><p3><sg>' : '<vblex>',
	'<vblex><pron><cni><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><cni><p2><pl>' : '<vblex><pron>',
	'<vblex><pron><cni><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><cni><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><fti><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><fti><p1><sg>' : '<vblex><pron>',
	'<vblex><pron><fti><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><fti><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><ger>' : '<vblex><pron>',
	'<vblex><pron><ifi><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><ifi><p1><sg>' : '<vblex><pron>',
	'<vblex><pron><ifi><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><ifi><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><imp><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><imp><p2><pl>' : '<vblex><pron>',
	'<vblex><pron><imp><p2><sg>' : '<vblex><pron>',
	'<vblex><pron><imp><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><imp><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><inf>' : '<vblex><pron>',
	'<vblex><pron><pii><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><pii><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><pii><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><pis><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><pis><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><pis><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><pp><f><pl>' : '<vblex><pron>',
	'<vblex><pron><pp><f><sg>' : '<vblex><pron>',
	'<vblex><pron><pp><m><pl>' : '<vblex><pron>',
	'<vblex><pron><pp><m><sg>' : '<vblex><pron>',
	'<vblex><pron><pri><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><pri><p1><sg>' : '<vblex><pron>',
	'<vblex><pron><pri><p2><sg>' : '<vblex><pron>',
	'<vblex><pron><pri><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><pri><p3><sg>' : '<vblex><pron>',
	'<vblex><pron><prs><p1><pl>' : '<vblex><pron>',
	'<vblex><pron><prs><p2><sg>' : '<vblex><pron>',
	'<vblex><pron><prs><p3><pl>' : '<vblex><pron>',
	'<vblex><pron><prs><p3><sg>' : '<vblex><pron>',
	'<vblex><prs><p1><pl>' : '<vblex>',
	'<vblex><prs><p2><pl>' : '<vblex>',
	'<vblex><prs><p2><sg>' : '<vblex>',
	'<vblex><prs><p3><pl>' : '<vblex>',
	'<vblex><prs><p3><sg>' : '<vblex>',
	'<vbmod><cni><p1><pl>' : '<vbmod>',
	'<vbmod><cni><p2><pl>' : '<vbmod>',
	'<vbmod><cni><p2><sg>' : '<vbmod>',
	'<vbmod><cni><p3><pl>' : '<vbmod>',
	'<vbmod><cni><p3><sg>' : '<vbmod>',
	'<vbmod><fti><p1><pl>' : '<vbmod>',
	'<vbmod><fti><p1><sg>' : '<vbmod>',
	'<vbmod><fti><p2><pl>' : '<vbmod>',
	'<vbmod><fti><p2><sg>' : '<vbmod>',
	'<vbmod><fti><p3><pl>' : '<vbmod>',
	'<vbmod><fti><p3><sg>' : '<vbmod>',
	'<vbmod><fts><p1><pl>' : '<vbmod>',
	'<vbmod><fts><p3><sg>' : '<vbmod>',
	'<vbmod><ger>' : '<vbmod><ger>',
	'<vbmod><ifi><p1><pl>' : '<vbmod>',
	'<vbmod><ifi><p1><sg>' : '<vbmod>',
	'<vbmod><ifi><p2><pl>' : '<vbmod>',
	'<vbmod><ifi><p3><pl>' : '<vbmod>',
	'<vbmod><ifi><p3><sg>' : '<vbmod>',
	'<vbmod><imp><p1><pl>' : '<vbmod>',
	'<vbmod><imp><p2><pl>' : '<vbmod>',
	'<vbmod><imp><p2><sg>' : '<vbmod>',
	'<vbmod><imp><p3><pl>' : '<vbmod>',
	'<vbmod><imp><p3><sg>' : '<vbmod>',
	'<vbmod><inf>' : '<vbmod><inf>',
	'<vbmod><pii><p1><pl>' : '<vbmod>',
	'<vbmod><pii><p2><pl>' : '<vbmod>',
	'<vbmod><pii><p2><sg>' : '<vbmod>',
	'<vbmod><pii><p3><pl>' : '<vbmod>',
	'<vbmod><pii><p3><sg>' : '<vbmod>',
	'<vbmod><pis><p1><pl>' : '<vbmod>',
	'<vbmod><pis><p3><pl>' : '<vbmod>',
	'<vbmod><pis><p3><sg>' : '<vbmod>',
	'<vbmod><pp><f><pl>' : '<vbmod><pp>',
	'<vbmod><pp><f><sg>' : '<vbmod><pp>',
	'<vbmod><pp><m><pl>' : '<vbmod><pp>',
	'<vbmod><pp><m><sg>' : '<vbmod><pp>',
	'<vbmod><pri><p1><pl>' : '<vbmod>',
	'<vbmod><pri><p1><sg>' : '<vbmod>',
	'<vbmod><pri><p2><pl>' : '<vbmod>',
	'<vbmod><pri><p2><sg>' : '<vbmod>',
	'<vbmod><pri><p3><pl>' : '<vbmod>',
	'<vbmod><pri><p3><sg>' : '<vbmod>',
	'<vbmod><prs><p1><pl>' : '<vbmod>',
	'<vbmod><prs><p2><pl>' : '<vbmod>',
	'<vbmod><prs><p2><sg>' : '<vbmod>',
	'<vbmod><prs><p3><pl>' : '<vbmod>',
	'<vbmod><prs><p3><sg>' : '<vbmod>',
	'<vbser><cni><p1><pl>' : '<vbser>',
	'<vbser><cni><p2><pl>' : '<vbser>',
	'<vbser><cni><p3><pl>' : '<vbser>',
	'<vbser><cni><p3><sg>' : '<vbser>',
	'<vbser><fti><p1><pl>' : '<vbser>',
	'<vbser><fti><p1><sg>' : '<vbser>',
	'<vbser><fti><p2><pl>' : '<vbser>',
	'<vbser><fti><p2><sg>' : '<vbser>',
	'<vbser><fti><p3><pl>' : '<vbser>',
	'<vbser><fti><p3><sg>' : '<vbser>',
	'<vbser><fts><p3><pl>' : '<vbser>',
	'<vbser><fts><p3><sg>' : '<vbser>',
	'<vbser><ger>' : '<vbser><ger>',
	'<vbser><ifi><p1><pl>' : '<vbser>',
	'<vbser><ifi><p1><sg>' : '<vbser>',
	'<vbser><ifi><p3><pl>' : '<vbser>',
	'<vbser><ifi><p3><sg>' : '<vbser>',
	'<vbser><imp><p2><pl>' : '<vbser>',
	'<vbser><imp><p2><sg>' : '<vbser>',
	'<vbser><imp><p3><pl>' : '<vbser>',
	'<vbser><imp><p3><sg>' : '<vbser>',
	'<vbser><inf>' : '<vbser><inf>',
	'<vbser><pii><p1><pl>' : '<vbser>',
	'<vbser><pii><p2><sg>' : '<vbser>',
	'<vbser><pii><p3><pl>' : '<vbser>',
	'<vbser><pii><p3><sg>' : '<vbser>',
	'<vbser><pis><p1><pl>' : '<vbser>',
	'<vbser><pis><p2><sg>' : '<vbser>',
	'<vbser><pis><p3><pl>' : '<vbser>',
	'<vbser><pis><p3><sg>' : '<vbser>',
	'<vbser><pp><m><sg>' : '<vbser><pp>',
	'<vbser><pri><p1><pl>' : '<vbser>',
	'<vbser><pri><p1><sg>' : '<vbser>',
	'<vbser><pri><p2><pl>' : '<vbser>',
	'<vbser><pri><p2><sg>' : '<vbser>',
	'<vbser><pri><p3><pl>' : '<vbser>',
	'<vbser><pri><p3><sg>' : '<vbser>',
	'<vbser><prs><p1><pl>' : '<vbser>',
	'<vbser><prs><p2><sg>' : '<vbser>',
	'<vbser><prs><p3><pl>' : '<vbser>',
	'<vbser><prs><p3><sg>' : '<vbser>',
	'<web>' : '<web>'
};

en_table = {
	'<adj>' : '<adj>',
	'<adj><comp>' : '<adj>',
	'<adj><pos>' : '<adj><pos>',
	'<adj><sint>' : '<adj>',
	'<adj><sint><comp>' : '<adj>',
	'<adj><sint><sup>' : '<adj>',
	'<adj><sup>' : '<adj>',
	'<adv>' : '<adv>',
	'<adv><itg>' : '<adv><itg>',
	'<apos>' : '<apos>',
	'<cm>' : '<cm>',
	'<cnjadv>' : '<cnjadv>',
	'<cnjcoo>' : '<cnjcoo>',
	'<cnjsub>' : '<cnjsub>',
	'<det><def><sp>' : '<def><def>',
	'<det><dem><pl>' : '<det><dem>',
	'<det><dem><sg>' : '<det><dem>',
	'<det><ind><pl>' : '<det><ind>',
	'<det><ind><sg>' : '<det><ind>',
	'<det><ind><sp>' : '<det><ind>',
	'<det><itg><pl>' : '<det><itg>',
	'<det><itg><sg>' : '<det><itg>',
	'<det><itg><sp>' : '<det><itg>',
	'<det><ord><sp>' : '<det><ord>',
	'<det><pos><sp>' : '<det><pos>',
	'<det><qnt><pl>' : '<det><qnt>',
	'<det><qnt><sg>' : '<det><qnt>',
	'<det><qnt><sp>' : '<det><qnt>',
	'<gen>' : '<gen>',
	'<guio>' : '<guio>',
	'<ij>' : '<ij>',
	'<lpar>' : '<lpar>',
	'<lquest>' : '<lquest>',
	'<mon>' : '<mon>',
	'<n><acr><sg>' : '<n>',
	'<np><al><pl>' : '<np>',
	'<np><al><sg>' : '<np>',
	'<np><ant><f><sg>' : '<np><ant>',
	'<np><ant><mf><sg>' : '<np><ant>',
	'<np><ant><m><sg>' : '<np><ant>',
	'<np><cog><pl>' : '<np><cog>',
	'<np><cog><sg>' : '<np><cog>',
	'<n><pl>' : '<n>',
	'<np><loc><pl>' : '<np><loc>',
	'<np><loc><sg>' : '<np><loc>',
	'<n><sg>' : '<n>',
	'<num>' : '<num>',
	'<num><mf><sg>' : '<num>',
	'<num><ord>' : '<num><ord>',
	'<num><percent>' : '<num><percent>',
	'<num><pl>' : '<num>',
	'<num><sg>' : '<num>',
	'<num><sp>' : '<num>',
	'<pr>' : '<pr>',
	'<preadv>' : '<preadv>',
	'<predet><sp>' : '<predet>',
	'<prn><itg><mf><pl>' : '<prn><itg>',
	'<prn><itg><mf><sg>' : '<prn><itg>',
	'<prn><itg><mf><sp>' : '<prn><itg>',
	'<prn><itg><m><sg>' : '<prn><itg>',
	'<prn><itg><m><sp>' : '<prn><itg>',
	'<prn><obj><p1><mf><pl>' : '<prn><obj>',
	'<prn><obj><p1><mf><sg>' : '<prn><obj>',
	'<prn><obj><p2><mf><sp>' : '<prn><obj>',
	'<prn><obj><p3><f><sg>' : '<prn><obj>',
	'<prn><obj><p3><mf><pl>' : '<prn><obj>',
	'<prn><obj><p3><m><sg>' : '<prn><obj>',
	'<prn><obj><p3><nt><sg>' : '<prn><obj>',
	'<prn><pos><mf><sp>' : '<prn><pos>',
	'<prn><ref><p1><mf><pl>' : '<prn><ref>',
	'<prn><ref><p1><mf><sg>' : '<prn><ref>',
	'<prn><ref><p2><mf><pl>' : '<prn><ref>',
	'<prn><ref><p2><mf><sg>' : '<prn><ref>',
	'<prn><ref><p3><f><sg>' : '<prn><ref>',
	'<prn><ref><p3><mf><pl>' : '<prn><ref>',
	'<prn><ref><p3><m><sg>' : '<prn><ref>',
	'<prn><ref><p3><nt><sg>' : '<prn><ref>',
	'<prn><subj><p1><mf><pl>' : '<prn><subj>',
	'<prn><subj><p1><mf><sg>' : '<prn><subj>',
	'<prn><subj><p2><mf><sp>' : '<prn><subj>',
	'<prn><subj><p3><f><sg>' : '<prn><subj>',
	'<prn><subj><p3><mf><pl>' : '<prn><subj>',
	'<prn><subj><p3><m><sg>' : '<prn><subj>',
	'<prn><subj><p3><nt><sg>' : '<prn><subj>',
	'<prn><tn><mf><pl>' : '<prn><tn>',
	'<prn><tn><mf><sg>' : '<prn><tn>',
	'<prn><tn><mf><sp>' : '<prn><tn>',
	'<prn><tn><m><sg>' : '<prn><tn>',
	'<prn><tn><nt><sg>' : '<prn><tn>',
	'<rel><aa><mf><sp>' : '<rel><aa>',
	'<rel><adv>' : '<rel><adv>',
	'<rel><an><mf><sp>' : '<rel><an>',
	'<rel><nn><mf><pl>' : '<rel><nn>',
	'<rel><nn><mf><sg>' : '<rel><nn>',
	'<rel><nn><mf><sp>' : '<rel><nn>',
	'<rpar>' : '<rpar>',
	'<sent>' : '<sent>',
	'<vaux><inf>' : '<vaux><inf>',
	'<vaux><past>' : '<vaux>',
	'<vaux><pres>' : '<vaux>',
	'<vbdo><past>' : '<vbdo>',
	'<vbdo><pres>' : '<vbdo>',
	'<vbdo><pri><p3><sg>' : '<vbdo>',
	'<vbhaver><ger>' : '<vbhaver><ger>',
	'<vbhaver><inf>' : '<vbhaver><inf>',
	'<vbhaver><past>' : '<vbhaver>',
	'<vbhaver><pres>' : '<vbhaver>',
	'<vbhaver><pri><p3><sg>' : '<vbhaver>',
	'<vblex><ger>' : '<vblex><ger>',
	'<vblex><inf>' : '<vblex><inf>',
	'<vblex><past>' : '<vblex>',
	'<vblex><past><p3><sg>' : '<vblex>',
	'<vblex><pp>' : '<vblex><pp>',
	'<vblex><pres>' : '<vblex>',
	'<vblex><pri><p1><sg>' : '<vblex>',
	'<vblex><pri><p3><sg>' : '<vblex>',
	'<vblex><sep><ger>' : '<vblex><ger>',
	'<vblex><sep><inf>' : '<vblex><inf>',
	'<vblex><sep><past>' : '<vblex>',
	'<vblex><sep><pp>' : '<vblex><pp>',
	'<vblex><sep><pres>' : '<vblex>',
	'<vblex><sep><pri><p3><sg>' : '<vblex>',
	'<vbmod><ger>' : '<vbmod><ger>',
	'<vbmod><inf>' : '<vbmod><inf>',
	'<vbmod><past>' : '<vbmod>',
	'<vbmod><pp>' : '<vbmod><pp>',
	'<vbmod><pres>' : '<vbmod>',
	'<vbmod><pri><p3><sg>' : '<vbmod>',
	'<vbser><ger>' : '<vbser><ger>',
	'<vbser><inf>' : '<vbser><inf>',
	'<vbser><past>' : '<vbser>',
	'<vbser><past><p1><sg>' : '<vbser>',
	'<vbser><past><p3><sg>' : '<vbser>',
	'<vbser><pp>' : '<vbser><pp>',
	'<vbser><pres>' : '<vbser>',
	'<vbser><pri><p1><sg>' : '<vbser>',
	'<vbser><pri><p3><sg>' : '<vbser>',
	'<web>' : '<web>',
};

table = {};

if len(sys.argv) != 2: #{
	print 'process-tagger-output.py <lang>';
	sys.exit();
#}

if sys.argv[1] == 'en': #{
	table = en_table; 
elif sys.argv[1] == 'es': #{
	table = es_table; 
else: #{
	print 'process-tagger-output.py <lang>';
	sys.exit();
#}

def processWord(c): #{
	lemma = '';
	tags = '';

	c = sys.stdin.read(1);
	while c != '<': #{
		if c == '*': #{
			while c and c != '$': #{
				lemma = lemma + c;
				c = sys.stdin.read(1);
			#}
			sys.stdout.write(lemma.replace(' ', '~') + ' ');
			return;
		#}
		lemma = lemma + c;
		c = sys.stdin.read(1);
	#}

	while c != '$': #{
		tags = tags + c;
		c = sys.stdin.read(1);
	#}
	
	sys.stdout.write(lemma.replace(' ', '~') + table[tags] + ' ');
#}

while c: #{
	# Beginning of a lexical unit
	if c == '^': #{
		processWord(c);
	#}

	if c == '[': #{

		while c and c != ']': #{

			if c == '\n': #{
				sys.stdout.write('\n');
			#}
			c = sys.stdin.read(1);
		#}
	#}

	# Newline is newline
	if c == '\n': #{
		sys.stdout.write('\n');
	#}

	c = sys.stdin.read(1);
#}

